/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usage
         * @description Bugunku kota tuketimi, calistirma dagilimi ve devre disi saglayicilar.
         */
        get: operations["usage_api_admin_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Oturumu SUNUCUDAN siler; cerezi silmek tek basina yeterli olmazdi.
         *
         *     Cerez silinip kayit dursaydi, o jetonun bir kopyasini ele geciren biri
         *     oturumu kullanmaya devam ederdi. Sunucu tarafli oturumlarin varlik sebebi
         *     de bu: iptal edilebilir olmalari.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description Kim giris yapmis. Oturum YOKSA hata degil, `signed_in: false` doner.
         *
         *     401 donmuyor cunku bu ucun isi tam da "oturum var mi" sorusunu yanitlamak;
         *     arayuz her acilista bunu cagirip giris ekrani gosterip gostermeyecegine
         *     karar veriyor.
         */
        get: operations["whoami_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/youtube": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect */
        delete: operations["disconnect_api_auth_youtube_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/youtube/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Youtube Callback
         * @description Google'in geri dondugu uc. Kodu jetona cevirir, kimligi kurar.
         *
         *     Bu uc AYNI ANDA iki is yapiyor: YouTube yayin izni aliyor ve kullaniciyi
         *     tanitiyor. Ayirmak ikinci bir onay ekrani demekti; kullanici zaten yayin
         *     icin Google hesabi bagliyor.
         */
        get: operations["youtube_callback_api_auth_youtube_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/youtube/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start Authorization
         * @description Google onay URL'ini uretir. Tarayici bu adrese YONLENDIRILIR.
         *
         *     OTURUM GEREKTIRMIYOR -- gerektirseydi giris yapmak icin once giris yapmis
         *     olmak gerekirdi. Kullanicinin API anahtarlarina da bakmiyor: OAuth istemcisi
         *     kuruluma ait ve akisin bu adimi kimlikten bagimsiz.
         */
        get: operations["start_authorization_api_auth_youtube_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/youtube/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description Hesap bagli mi, ve baglanti kurulabilir mi?
         */
        get: operations["get_status_api_auth_youtube_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Capabilities
         * @description Hangi ozelliklerin kullanilabilir oldugunu bildirir.
         *
         *     SIR DONDURMEZ: yalnizca "kurulu mu" bilgisi ve calistirma varsayilanlari.
         *     Anahtar degerleri hicbir kosulda bu ucun cevabina girmez.
         */
        get: operations["get_capabilities_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /**
         * Create Run
         * @description Calistirmayi kuyruga alir ve HEMEN doner.
         *
         *     `build_playlist` 4-40 sn (ASR acikken dakikalar) suruyor; istegi bu sure
         *     boyunca acik tutmak yerine is numarasi donup ilerlemeyi SSE ile akitiyoruz.
         */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Tamamlanmis sonucu dondurur.
         *
         *     Once bellekteki is durumuna, sonra kalici gecmise bakar: surec yeniden
         *     baslamis olsa bile tamamlanmis calistirmalar okunabilir.
         */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Or Delete Run
         * @description Calisan isi iptal eder; bitmis calistirmayi gecmisten siler.
         *
         *     Iptal dali SAHIPLIK KONTROLUNDEN geciyor. Onceki hali dogrudan
         *     `runner.cancel(run_id)` cagiriyordu; silme dali `user_id` suzuyor olsa da
         *     iptal dali sizmiyordu, yani cok kullanicili kuruluma gecildiginde kimligi
         *     bilen herkes baskasinin calisan isini durdurabilirdi.
         *
         *     Silme DISKE de dokunuyor (bkz. `run_retention.delete_run`): eskiden yalnizca
         *     veritabani satirlari gidiyor, calisma plani ve sonuc JSON'u diskte kaliyordu.
         */
        delete: operations["cancel_or_delete_run_api_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description Ilerleme olaylarini SSE olarak akitir.
         *
         *     Tarayici baglanti koptugunda `Last-Event-ID` basligiyla geri doner; akis o
         *     indeksten devam eder, kacirilan ilerleme kaybolmaz. Zaten bitmis bir is icin
         *     birikmis olaylar + son durum tek seferde yollanip kapanir.
         */
        get: operations["stream_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/export/{artifact}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Export
         * @description Uretilen JSON / Markdown dosyasini indirir.
         */
        get: operations["download_export_api_runs__run_id__export__artifact__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Run
         * @description Tamamlanmis bir calistirmayi YouTube playlist'i olarak yayinlar.
         *
         *     Build'den AYRI: yayinlama basarisiz olsa da playlist uretimi kaybolmasin,
         *     ve kullanici yetkilendirmeyi sonradan yapip tekrar deneyebilsin.
         */
        post: operations["publish_run_api_runs__run_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description SSE kullanmayan istemciler icin yoklama ucu.
         */
        get: operations["get_status_api_runs__run_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Spaces */
        get: operations["list_spaces_api_spaces_get"];
        put?: never;
        /** Create Space */
        post: operations["create_space_api_spaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{space_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Space */
        get: operations["get_space_api_spaces__space_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Space
         * @description Alani veritabanindan ve DISKTEN siler.
         */
        delete: operations["delete_space_api_spaces__space_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{space_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description Alandaki kaynaklara dayanarak soruyu yanitlar.
         *
         *     SENKRON: tek bir erisim + tek bir LLM cagrisi, olculen sure birkac saniye.
         *     Arka plana atmak, istemciye ikinci bir akis mekanizmasi tasittirirdi ve
         *     kazanci yoktu.
         *
         *     `answered=False` bir HATA DEGIL, 200 ile donuyor. Ozelligin asil vaadi bu
         *     ve onu HTTP hatasi yapmak, arayuzun onu kirmizi bir kutuda gostermesine ve
         *     kullanicinin sistemi bozuk sanmasina yol acardi.
         */
        post: operations["ask_api_spaces__space_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{space_id}/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Ingest Events
         * @description Iceri alma ilerlemesini SSE olarak akitir. `runs` ile AYNI mekanizma.
         */
        get: operations["stream_ingest_events_api_spaces__space_id__jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{space_id}/sources/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Document Source
         * @description Bir dokuman yukler ve indekslemeyi kuyruga alir.
         *
         *     Dosya SENKRON yaziliyor, indeksleme arka planda: yazma hizlidir ve
         *     basarisiz olursa kullanici bunu ANINDA ogrenmeli (boyut/tur reddi bir
         *     arka plan isinin icinde kaybolmamali).
         */
        post: operations["add_document_source_api_spaces__space_id__sources_document_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{space_id}/sources/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Run Source
         * @description Tamamlanmis bir calistirmanin videolarini alana ekler.
         *
         *     HEMEN doner: transkript cekme + parcalama + gomme dakikalar surebiliyor
         *     (ASR acikken daha da fazla) ve bir HTTP istegi bunu bekleyemez.
         */
        post: operations["add_run_source_api_spaces__space_id__sources_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{space_id}/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Source
         * @description Kaynagi, parcalarini ve (dokumansa) diskteki dosyasini siler.
         *
         *     `{source_id:path}` cunku kimlik `doc:0a1b.pdf` bicimde ve iki nokta
         *     tasiyor; varsayilan yol donusturucu bunu sorunsuz gecirse de bicimi
         *     acikca belirtmek ileride ayrac degisirse kirilmayi onluyor.
         */
        delete: operations["delete_source_api_spaces__space_id__sources__source_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddRunSourceRequest */
        AddRunSourceRequest: {
            /** Run Id */
            run_id: string;
        };
        /** AskRequest */
        AskRequest: {
            /**
             * Language
             * @default Türkçe
             */
            language?: string;
            /** Question */
            question: string;
        };
        /** Body_add_document_source_api_spaces__space_id__sources_document_post */
        Body_add_document_source_api_spaces__space_id__sources_document_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Title */
            title?: string | null;
        };
        /**
         * CapabilitiesResponse
         * @description Arayuzun hangi kontrolleri acabilecegi. SIR ICERMEZ.
         *
         *     `AppConfig.public_capabilities()` ile bu modelin alanlari BIREBIR ayni
         *     olmali: `CapabilitiesResponse(**capabilities)` fazladan anahtarlari
         *     sessizce YOK SAYAR (pydantic'in varsayilan `extra="ignore"` davranisi).
         *     `llm_configured` tam bu yuzden hic API'ye cikmiyordu -- Together saglayici
         *     islerinde `public_capabilities()`e eklenmisti ama buraya eklenmemisti;
         *     tip kontrolu (`contract.ts`) frontend tipine eklenince farki yakaladi.
         */
        CapabilitiesResponse: {
            /** Asr Available */
            asr_available: boolean;
            /** Cookies Configured */
            cookies_configured: boolean;
            /** Defaults */
            defaults: {
                [key: string]: unknown;
            };
            /** Gemini Configured */
            gemini_configured: boolean;
            /** Llm Configured */
            llm_configured: boolean;
            /**
             * Rag Available
             * @default false
             */
            rag_available: boolean;
            /** Runs Remaining Today */
            runs_remaining_today: number | null;
            /**
             * Service Capacity Reached
             * @default false
             */
            service_capacity_reached: boolean;
            /** Youtube Publish Configured */
            youtube_publish_configured: boolean;
            /** Youtube Search Configured */
            youtube_search_configured: boolean;
        };
        /**
         * Citation
         * @description Yanitin dayandigi tek bir parcaya isaret.
         *
         *     `url` video icin zaman damgasi GOMULU gelir (`...&t=123s`), yani tiklayan
         *     kullanici dogrudan o ana gider. Zaman bilinmiyorsa (segment tasimayan eski
         *     bir transkript) saniye EKLENMEZ -- uydurulmus bir saniye, kullaniciyi
         *     alakasiz bir yere goturur ve konumsuz bir alintidan kotudur.
         */
        Citation: {
            /** Page */
            page: number | null;
            /** Quote */
            quote: string;
            /** Source Id */
            source_id: string;
            /** Start Sec */
            start_sec: number | null;
            /** Title */
            title: string;
            /** Url */
            url: string | null;
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /**
             * Create Youtube Playlist
             * @default false
             */
            create_youtube_playlist?: boolean;
            filters?: components["schemas"]["FilterOptions"];
            options?: components["schemas"]["RunOptionsOverride"];
            /** Topic */
            topic: string;
        };
        /** CreateSpaceRequest */
        CreateSpaceRequest: {
            /** Name */
            name: string;
        };
        /** ExportArtifacts */
        ExportArtifacts: {
            /** Json Path */
            json_path: string;
            /** Markdown Path */
            markdown_path: string;
        };
        /** FilterOptions */
        FilterOptions: {
            /**
             * Difficulty
             * @default mixed
             * @enum {string}
             */
            difficulty?: "beginner" | "intermediate" | "advanced" | "mixed";
            /**
             * Freshness Preference
             * @default balanced
             * @enum {string}
             */
            freshness_preference?: "balanced" | "evergreen" | "recent";
            /**
             * Include English
             * @default false
             */
            include_english?: boolean;
            /**
             * Language
             * @default en
             */
            language?: string;
            /**
             * Max Duration Minutes
             * @default 60
             */
            max_duration_minutes?: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestAccepted
         * @description 202 yaniti: iceri alma kuyruga alindi.
         *
         *     Uc adres `runs` ile AYNI deseni izliyor -- istemci tarafinda tek bir
         *     ilerleme akisi mantigi iki ozelligi birden kapsayabilsin diye.
         */
        IngestAccepted: {
            /** Events Url */
            events_url: string;
            /** Job Id */
            job_id: string;
            /** Space Id */
            space_id: string;
        };
        /** MetadataScore */
        MetadataScore: {
            /** Channel Quality */
            channel_quality: number;
            /** Description Relevance */
            description_relevance: number;
            /**
             * Difficulty Fit
             * @default 0
             */
            difficulty_fit: number;
            /** Duration Fit */
            duration_fit: number;
            /** Engagement */
            engagement: number;
            /** Freshness */
            freshness: number;
            /** Language Match */
            language_match: number;
            /** Rationale */
            rationale: string[];
            /** Title Relevance */
            title_relevance: number;
            /** Total */
            total: number;
        };
        /** PlaylistResult */
        PlaylistResult: {
            /** Created At */
            created_at: string;
            exports: components["schemas"]["ExportArtifacts"] | null;
            filters: components["schemas"]["FilterOptions"];
            /** Published Playlist Url */
            published_playlist_url: string | null;
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
            /** Run Id */
            run_id: string;
            /** Study Notes */
            study_notes: components["schemas"]["StudyNote"][];
            /** Subtopics */
            subtopics: components["schemas"]["SubtopicResult"][];
            /** Topic */
            topic: string;
            /** Warnings */
            warnings: string[];
        };
        /** ProgressEvent */
        ProgressEvent: {
            /**
             * Current
             * @default null
             */
            current: number | null;
            /** Message */
            message: string;
            /** Progress */
            progress: number;
            /** Stage */
            stage: string;
            /**
             * Total
             * @default null
             */
            total: number | null;
        };
        /** PublishResponse */
        PublishResponse: {
            /** Added */
            added: number;
            /** Url */
            url: string;
            /** Warnings */
            warnings: string[];
        };
        /**
         * RagAnswer
         * @description Bir soruya verilen yanit -- ya da verilemedigi bilgisi.
         *
         *     `answered=False` BIRINCI SINIF bir sonuc, hata degil. Havuzda cevabi
         *     olmayan bir soruya cevap URETMEK, bu projenin her yerinde reddedilen seyin
         *     ta kendisi (`StudyNote.no_transcript`, `interrupted` calistirma durumu,
         *     "zayif eslesme" etiketi): bilinmeyeni bilinmeyen olarak isaretlemek, tahmin
         *     uretmekten iyidir.
         *
         *     `searched_sources` seffaflik icin: kullanici eksik olanin kendi sorusu mu
         *     yoksa havuzu mu oldugunu gorebilmeli.
         */
        RagAnswer: {
            /** Answer */
            answer: string | null;
            /** Answered */
            answered: boolean;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Reason */
            reason: string | null;
            /**
             * Searched Sources
             * @default 0
             */
            searched_sources: number;
        };
        /** Recommendation */
        Recommendation: {
            /** Confidence Score */
            confidence_score: number;
            metadata_score: components["schemas"]["MetadataScore"];
            /** Position */
            position: number;
            /** Subtopic */
            subtopic: string;
            /** Transcript Backend */
            transcript_backend: string | null;
            /** Transcript Source */
            transcript_source: string | null;
            /**
             * Transcript Status
             * @enum {string}
             */
            transcript_status: "available" | "unavailable" | "cooldown" | "failed_temporary" | "failed_permanent";
            video: components["schemas"]["VideoCandidate"];
            /** Why Selected */
            why_selected: string;
        };
        /**
         * RunAccepted
         * @description 202 yaniti: is kuyruga alindi, kimlik hazir.
         */
        RunAccepted: {
            /** Events Url */
            events_url: string;
            /** Result Url */
            result_url: string;
            /** Run Id */
            run_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "done" | "failed" | "cancelled" | "interrupted";
        };
        /** RunListResponse */
        RunListResponse: {
            /** Items */
            items: components["schemas"]["RunSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * RunOptionsOverride
         * @description Calistirma basina ezilebilen ayarlar. Verilmeyenler sunucu varsayilaninda kalir.
         */
        RunOptionsOverride: {
            /** Channel Repeat Penalty */
            channel_repeat_penalty?: number | null;
            /** Enable Asr Fallback */
            enable_asr_fallback?: boolean | null;
            /** Enable Study Notes */
            enable_study_notes?: boolean | null;
            /** Gemini Model */
            gemini_model?: string | null;
            /** Max Asr Videos Per Run */
            max_asr_videos_per_run?: number | null;
            /** Max Subtopics */
            max_subtopics?: number | null;
            /** Metadata Top K */
            metadata_top_k?: number | null;
            /** Search Candidates Per Subtopic */
            search_candidates_per_subtopic?: number | null;
            /** Transcript Enrichment Top K */
            transcript_enrichment_top_k?: number | null;
            /** Youtube Playlist Privacy Status */
            youtube_playlist_privacy_status?: ("private" | "unlisted" | "public") | null;
        };
        /** RunResultResponse */
        RunResultResponse: {
            result: components["schemas"]["PlaylistResult"] | null;
            /** Run Id */
            run_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "done" | "failed" | "cancelled" | "interrupted";
        };
        /**
         * RunSnapshotBody
         * @description SSE `done` olayinin govdesi: durum + `created_at`.
         *
         *     `RunStatus`tan TUREMESI kasitli -- alanlari elle tekrarlamak ikisinin
         *     sessizce ayrisabilecegi anlamina geliyordu.
         *
         *     REST yaniti DEGIL, bu yuzden FastAPI onu kendiliginden OpenAPI'ye koymuyor;
         *     `scripts/dump_openapi.py` acikca ekliyor. Boyle bir modele bagli olmasinin
         *     sebebi: govde eskiden dogrudan `JobHandle.snapshot()` sozlugu olarak
         *     yollaniyordu ve is katmaninin IC alan adlari (`job_id`) tel uzerine
         *     siziyordu. Frontend `run_id` bekledigi icin o alan calisma zamaninda
         *     `undefined` kaliyordu; TypeScript ise `string` oldugunu iddia ediyordu.
         */
        RunSnapshotBody: {
            /** Created At */
            created_at: string;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Message
             * @default null
             */
            message: string | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Run Id */
            run_id: string;
            /**
             * Stage
             * @default null
             */
            stage: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "done" | "failed" | "cancelled" | "interrupted";
        };
        /**
         * RunStatus
         * @description Bir calistirmanin o anki durumu; `/{run_id}/status` yaniti.
         */
        RunStatus: {
            /** Error */
            error: string | null;
            /** Message */
            message: string | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Run Id */
            run_id: string;
            /** Stage */
            stage: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "done" | "failed" | "cancelled" | "interrupted";
        };
        /** RunSummary */
        RunSummary: {
            /** Created At */
            created_at: string;
            /** Filters */
            filters: {
                [key: string]: unknown;
            };
            /** Is Complete */
            is_complete: boolean;
            /** Run Id */
            run_id: string;
            /** Topic */
            topic: string;
        };
        /**
         * SpaceDetail
         * @description Alan + kaynaklari.
         *
         *     `SpaceSummary`den TUREMESI kasitli: alanlari elle tekrarlamak ikisinin
         *     sessizce ayrisabilecegi anlamina gelirdi (ayni gerekce `RunSnapshotBody`
         *     icin de yazili).
         */
        SpaceDetail: {
            /**
             * Chunk Count
             * @default 0
             */
            chunk_count: number;
            /** Created At */
            created_at: string;
            /** Name */
            name: string;
            /**
             * Source Count
             * @default 0
             */
            source_count: number;
            /** Sources */
            sources: components["schemas"]["SpaceSource"][];
            /** Space Id */
            space_id: string;
            /** Updated At */
            updated_at: string;
        };
        /** SpaceListResponse */
        SpaceListResponse: {
            /** Items */
            items: components["schemas"]["SpaceSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * SpaceSource
         * @description Bir ogrenme alanindaki tek bir kaynak (video ya da dokuman).
         */
        SpaceSource: {
            /**
             * Chunk Count
             * @default 0
             */
            chunk_count: number;
            /** Error */
            error: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "video" | "document";
            /** Language */
            language: string | null;
            /** Ref Id */
            ref_id: string;
            /** Source Id */
            source_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "indexed" | "no_text" | "failed";
            /** Title */
            title: string;
            /** Url */
            url: string | null;
        };
        /** SpaceSummary */
        SpaceSummary: {
            /**
             * Chunk Count
             * @default 0
             */
            chunk_count: number;
            /** Created At */
            created_at: string;
            /** Name */
            name: string;
            /**
             * Source Count
             * @default 0
             */
            source_count: number;
            /** Space Id */
            space_id: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * StudyNote
         * @description Bir alt konu icin transkriptten uretilen calisma notu.
         *
         *     "no_transcript" AYRI bir durum: transkripti olmayan bir video icin not
         *     UYDURULMUYOR. Bu, projenin geri kalaninda kurulu davranisla ayni cizgide --
         *     `interrupted` calistirma durumu ve "zayif eslesme" etiketi de ayni sebeple
         *     var: bilinmeyeni bilinmeyen olarak isaretlemek, tahmin uretmekten iyidir.
         */
        StudyNote: {
            /** Content */
            content: string | null;
            /** Error */
            error: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "no_transcript" | "failed";
            /** Subtopic */
            subtopic: string;
            /** Video Id */
            video_id: string;
        };
        /** Subtopic */
        Subtopic: {
            /** Match Terms */
            match_terms: string[];
            /** Normalized Title */
            normalized_title: string;
            /** Search Query */
            search_query: string | null;
            /** Search Query En */
            search_query_en: string | null;
            /** Source Titles */
            source_titles: string[];
            /** Title */
            title: string;
        };
        /** SubtopicResult */
        SubtopicResult: {
            /** Candidates Considered */
            candidates_considered: number;
            /** Notes */
            notes: string[];
            /** Query */
            query: string;
            /** Selected Video Id */
            selected_video_id: string | null;
            /** Shortlisted Candidates */
            shortlisted_candidates: components["schemas"]["VideoCandidate"][];
            subtopic: components["schemas"]["Subtopic"];
            /**
             * Transcript Status
             * @default unavailable
             * @enum {string}
             */
            transcript_status: "available" | "unavailable" | "cooldown" | "failed_temporary" | "failed_permanent";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VideoCandidate */
        VideoCandidate: {
            /** Channel */
            channel: string | null;
            /** Channel Id */
            channel_id: string | null;
            /** Channel Video Count */
            channel_video_count: number | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** Discovery Provider */
            discovery_provider: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            /**
             * Is Live
             * @default false
             */
            is_live: boolean;
            /** Language */
            language: string | null;
            /**
             * Metadata Score
             * @default 0
             */
            metadata_score: number;
            /** Publish Date */
            publish_date: string | null;
            /** Subscriber Count */
            subscriber_count: number | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Video Id */
            video_id: string;
            /** View Count */
            view_count: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    usage_api_admin_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    whoami_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    disconnect_api_auth_youtube_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    youtube_callback_api_auth_youtube_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_authorization_api_auth_youtube_start_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_status_api_auth_youtube_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_capabilities_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_or_delete_run_api_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export_api_runs__run_id__export__artifact__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                artifact: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_run_api_runs__run_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_runs__run_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_spaces_api_spaces_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_space_api_spaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_space_api_spaces__space_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_space_api_spaces__space_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_spaces__space_id__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RagAnswer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_ingest_events_api_spaces__space_id__jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_document_source_api_spaces__space_id__sources_document_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_document_source_api_spaces__space_id__sources_document_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_run_source_api_spaces__space_id__sources_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRunSourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_source_api_spaces__space_id__sources__source_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
