/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/youtube": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect */
        delete: operations["disconnect_api_auth_youtube_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/youtube/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Youtube Callback
         * @description Google'in geri dondugu uc. Kodu jetona cevirip kullaniciya baglar.
         */
        get: operations["youtube_callback_api_auth_youtube_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/youtube/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start Authorization
         * @description Google onay URL'ini uretir. Tarayici bu adrese YONLENDIRILIR.
         */
        get: operations["start_authorization_api_auth_youtube_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/youtube/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description Hesap bagli mi, ve baglanti kurulabilir mi?
         */
        get: operations["get_status_api_auth_youtube_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Capabilities
         * @description Hangi ozelliklerin kullanilabilir oldugunu bildirir.
         *
         *     SIR DONDURMEZ: yalnizca "kurulu mu" bilgisi ve calistirma varsayilanlari.
         *     Anahtar degerleri hicbir kosulda bu ucun cevabina girmez.
         */
        get: operations["get_capabilities_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /**
         * Create Run
         * @description Calistirmayi kuyruga alir ve HEMEN doner.
         *
         *     `build_playlist` 4-40 sn (ASR acikken dakikalar) suruyor; istegi bu sure
         *     boyunca acik tutmak yerine is numarasi donup ilerlemeyi SSE ile akitiyoruz.
         */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Tamamlanmis sonucu dondurur.
         *
         *     Once bellekteki is durumuna, sonra kalici gecmise bakar: surec yeniden
         *     baslamis olsa bile tamamlanmis calistirmalar okunabilir.
         */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Or Delete Run
         * @description Calisan isi iptal eder; bitmis calistirmayi gecmisten siler.
         */
        delete: operations["cancel_or_delete_run_api_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description Ilerleme olaylarini SSE olarak akitir.
         *
         *     Tarayici baglanti koptugunda `Last-Event-ID` basligiyla geri doner; akis o
         *     indeksten devam eder, kacirilan ilerleme kaybolmaz. Zaten bitmis bir is icin
         *     birikmis olaylar + son durum tek seferde yollanip kapanir.
         */
        get: operations["stream_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/export/{artifact}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Export
         * @description Uretilen JSON / Markdown dosyasini indirir.
         */
        get: operations["download_export_api_runs__run_id__export__artifact__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Run
         * @description Tamamlanmis bir calistirmayi YouTube playlist'i olarak yayinlar.
         *
         *     Build'den AYRI: yayinlama basarisiz olsa da playlist uretimi kaybolmasin,
         *     ve kullanici yetkilendirmeyi sonradan yapip tekrar deneyebilsin.
         */
        post: operations["publish_run_api_runs__run_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description SSE kullanmayan istemciler icin yoklama ucu.
         */
        get: operations["get_status_api_runs__run_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CapabilitiesResponse
         * @description Arayuzun hangi kontrolleri acabilecegi. SIR ICERMEZ.
         */
        CapabilitiesResponse: {
            /** Asr Available */
            asr_available: boolean;
            /** Cookies Configured */
            cookies_configured: boolean;
            /** Defaults */
            defaults: {
                [key: string]: unknown;
            };
            /** Gemini Configured */
            gemini_configured: boolean;
            /** Youtube Publish Configured */
            youtube_publish_configured: boolean;
            /** Youtube Search Configured */
            youtube_search_configured: boolean;
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /**
             * Create Youtube Playlist
             * @default false
             */
            create_youtube_playlist?: boolean;
            filters?: components["schemas"]["FilterOptions"];
            options?: components["schemas"]["RunOptionsOverride"];
            /** Topic */
            topic: string;
        };
        /** ExportArtifacts */
        ExportArtifacts: {
            /** Json Path */
            json_path: string;
            /** Markdown Path */
            markdown_path: string;
        };
        /** FilterOptions */
        FilterOptions: {
            /**
             * Difficulty
             * @default mixed
             * @enum {string}
             */
            difficulty?: "beginner" | "intermediate" | "advanced" | "mixed";
            /**
             * Freshness Preference
             * @default balanced
             * @enum {string}
             */
            freshness_preference?: "balanced" | "evergreen" | "recent";
            /**
             * Include English
             * @default false
             */
            include_english?: boolean;
            /**
             * Language
             * @default en
             */
            language?: string;
            /**
             * Max Duration Minutes
             * @default 60
             */
            max_duration_minutes?: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail: components["schemas"]["ValidationError"][];
        };
        /** MetadataScore */
        MetadataScore: {
            /** Channel Quality */
            channel_quality: number;
            /** Description Relevance */
            description_relevance: number;
            /**
             * Difficulty Fit
             * @default 0
             */
            difficulty_fit: number;
            /** Duration Fit */
            duration_fit: number;
            /** Engagement */
            engagement: number;
            /** Freshness */
            freshness: number;
            /** Language Match */
            language_match: number;
            /** Rationale */
            rationale: string[];
            /** Title Relevance */
            title_relevance: number;
            /** Total */
            total: number;
        };
        /** PlaylistResult */
        PlaylistResult: {
            /** Created At */
            created_at: string;
            exports: components["schemas"]["ExportArtifacts"] | null;
            filters: components["schemas"]["FilterOptions"];
            /** Published Playlist Url */
            published_playlist_url: string | null;
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
            /** Run Id */
            run_id: string;
            /** Subtopics */
            subtopics: components["schemas"]["SubtopicResult"][];
            /** Topic */
            topic: string;
            /** Warnings */
            warnings: string[];
        };
        /** ProgressEvent */
        ProgressEvent: {
            /**
             * Current
             * @default null
             */
            current: number | null;
            /** Message */
            message: string;
            /** Progress */
            progress: number;
            /** Stage */
            stage: string;
            /**
             * Total
             * @default null
             */
            total: number | null;
        };
        /** PublishResponse */
        PublishResponse: {
            /** Added */
            added: number;
            /** Url */
            url: string;
            /** Warnings */
            warnings: string[];
        };
        /** Recommendation */
        Recommendation: {
            /** Confidence Score */
            confidence_score: number;
            metadata_score: components["schemas"]["MetadataScore"];
            /** Position */
            position: number;
            /** Subtopic */
            subtopic: string;
            /** Transcript Backend */
            transcript_backend: string | null;
            /** Transcript Source */
            transcript_source: string | null;
            /**
             * Transcript Status
             * @enum {string}
             */
            transcript_status: "available" | "unavailable" | "cooldown" | "failed_temporary" | "failed_permanent";
            video: components["schemas"]["VideoCandidate"];
            /** Why Selected */
            why_selected: string;
        };
        /**
         * RunAccepted
         * @description 202 yaniti: is kuyruga alindi, kimlik hazir.
         */
        RunAccepted: {
            /** Events Url */
            events_url: string;
            /** Result Url */
            result_url: string;
            /** Run Id */
            run_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "done" | "failed" | "cancelled";
        };
        /** RunListResponse */
        RunListResponse: {
            /** Items */
            items: components["schemas"]["RunSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * RunOptionsOverride
         * @description Calistirma basina ezilebilen ayarlar. Verilmeyenler sunucu varsayilaninda kalir.
         */
        RunOptionsOverride: {
            /** Channel Repeat Penalty */
            channel_repeat_penalty?: number | null;
            /** Enable Asr Fallback */
            enable_asr_fallback?: boolean | null;
            /** Gemini Model */
            gemini_model?: string | null;
            /** Max Asr Videos Per Run */
            max_asr_videos_per_run?: number | null;
            /** Max Subtopics */
            max_subtopics?: number | null;
            /** Metadata Top K */
            metadata_top_k?: number | null;
            /** Search Candidates Per Subtopic */
            search_candidates_per_subtopic?: number | null;
            /** Transcript Enrichment Top K */
            transcript_enrichment_top_k?: number | null;
            /** Youtube Playlist Privacy Status */
            youtube_playlist_privacy_status?: ("private" | "unlisted" | "public") | null;
        };
        /** RunResultResponse */
        RunResultResponse: {
            result: components["schemas"]["PlaylistResult"] | null;
            /** Run Id */
            run_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "done" | "failed" | "cancelled";
        };
        /**
         * RunSnapshotBody
         * @description SSE `done` olayinin govdesi.
         *
         *     REST yaniti DEGIL, bu yuzden FastAPI onu kendiliginden OpenAPI'ye koymuyor;
         *     `scripts/dump_openapi.py` acikca ekliyor. Boyle bir modele bagli olmasinin
         *     sebebi: govde eskiden dogrudan `JobHandle.snapshot()` sozlugu olarak
         *     yollaniyordu ve is katmaninin IC alan adlari (`job_id`) tel uzerine
         *     siziyordu. Frontend `run_id` bekledigi icin o alan calisma zamaninda
         *     `undefined` kaliyordu; TypeScript ise `string` oldugunu iddia ediyordu.
         */
        RunSnapshotBody: {
            /** Created At */
            created_at: string;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Message
             * @default null
             */
            message: string | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Run Id */
            run_id: string;
            /**
             * Stage
             * @default null
             */
            stage: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "done" | "failed" | "cancelled";
        };
        /** RunStatus */
        RunStatus: {
            /** Error */
            error: string | null;
            /** Message */
            message: string | null;
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Run Id */
            run_id: string;
            /** Stage */
            stage: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "done" | "failed" | "cancelled";
        };
        /** RunSummary */
        RunSummary: {
            /** Created At */
            created_at: string;
            /** Filters */
            filters: {
                [key: string]: unknown;
            };
            /** Is Complete */
            is_complete: boolean;
            /** Run Id */
            run_id: string;
            /** Topic */
            topic: string;
        };
        /** Subtopic */
        Subtopic: {
            /** Normalized Title */
            normalized_title: string;
            /** Search Query */
            search_query: string | null;
            /** Search Query En */
            search_query_en: string | null;
            /** Source Titles */
            source_titles: string[];
            /** Title */
            title: string;
        };
        /** SubtopicResult */
        SubtopicResult: {
            /** Candidates Considered */
            candidates_considered: number;
            /** Notes */
            notes: string[];
            /** Query */
            query: string;
            /** Selected Video Id */
            selected_video_id: string | null;
            /** Shortlisted Candidates */
            shortlisted_candidates: components["schemas"]["VideoCandidate"][];
            subtopic: components["schemas"]["Subtopic"];
            /**
             * Transcript Status
             * @default unavailable
             * @enum {string}
             */
            transcript_status: "available" | "unavailable" | "cooldown" | "failed_temporary" | "failed_permanent";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VideoCandidate */
        VideoCandidate: {
            /** Channel */
            channel: string | null;
            /** Channel Id */
            channel_id: string | null;
            /** Channel Video Count */
            channel_video_count: number | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** Discovery Provider */
            discovery_provider: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            /**
             * Is Live
             * @default false
             */
            is_live: boolean;
            /** Language */
            language: string | null;
            /**
             * Metadata Score
             * @default 0
             */
            metadata_score: number;
            /** Publish Date */
            publish_date: string | null;
            /** Subscriber Count */
            subscriber_count: number | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Video Id */
            video_id: string;
            /** View Count */
            view_count: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    disconnect_api_auth_youtube_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    youtube_callback_api_auth_youtube_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_authorization_api_auth_youtube_start_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_status_api_auth_youtube_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_capabilities_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_or_delete_run_api_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export_api_runs__run_id__export__artifact__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                artifact: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_run_api_runs__run_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_runs__run_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
