from __future__ import annotations

from pathlib import Path

from src.config import AppConfig
from src.models import PlaylistResult


def create_youtube_playlist(config: AppConfig, result: PlaylistResult, logger=None) -> str:
    if not config.youtube_data_api_key:
        raise RuntimeError("YOUTUBE_DATA_API_KEY is required for official playlist creation")
    if not (
        config.youtube_oauth_client_secret_file
        or (config.youtube_oauth_client_id and config.youtube_oauth_client_secret)
    ):
        raise RuntimeError(
            "Set YOUTUBE_OAUTH_CLIENT_SECRET_FILE or both YOUTUBE_OAUTH_CLIENT_ID and "
            "YOUTUBE_OAUTH_CLIENT_SECRET for official playlist creation"
        )

    try:
        from google.oauth2.credentials import Credentials
        from google_auth_oauthlib.flow import InstalledAppFlow
        from googleapiclient.discovery import build
        from google.auth.transport.requests import Request
    except ImportError as exc:
        raise RuntimeError("Google OAuth dependencies are not installed") from exc

    token_path = Path(config.youtube_oauth_token_file)
    token_path.parent.mkdir(parents=True, exist_ok=True)
    scopes = ["https://www.googleapis.com/auth/youtube"]
    credentials = None
    if token_path.exists():
        credentials = Credentials.from_authorized_user_file(str(token_path), scopes=scopes)
    if not credentials or not credentials.valid:
        if credentials and credentials.expired and credentials.refresh_token:
            credentials.refresh(Request())
        else:
            flow = _build_installed_app_flow(config, scopes)
            credentials = flow.run_local_server(port=0)
        token_path.write_text(credentials.to_json(), encoding="utf-8")

    service = build("youtube", "v3", credentials=credentials)
    playlist = service.playlists().insert(
        part="snippet,status",
        body={
            "snippet": {
                "title": f"Learning Playlist: {result.topic}",
                "description": "Generated by Make A Playlist",
            },
            "status": {"privacyStatus": config.youtube_playlist_privacy_status},
        },
    ).execute()
    playlist_id = playlist["id"]
    for recommendation in result.recommendations:
        service.playlistItems().insert(
            part="snippet",
            body={
                "snippet": {
                    "playlistId": playlist_id,
                    "resourceId": {
                        "kind": "youtube#video",
                        "videoId": recommendation.video.video_id,
                    },
                }
            },
        ).execute()
    url = f"https://www.youtube.com/playlist?list={playlist_id}"
    if logger:
        logger.info("Created YouTube playlist %s", url)
    return url


def _build_installed_app_flow(config: AppConfig, scopes: list[str]):
    from google_auth_oauthlib.flow import InstalledAppFlow

    if config.youtube_oauth_client_secret_file:
        return InstalledAppFlow.from_client_secrets_file(config.youtube_oauth_client_secret_file, scopes=scopes)

    client_config = {
        "installed": {
            "client_id": config.youtube_oauth_client_id,
            "client_secret": config.youtube_oauth_client_secret,
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "redirect_uris": ["http://localhost"],
        }
    }
    return InstalledAppFlow.from_client_config(client_config, scopes=scopes)
