from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from src.config import AppConfig
from src.models import PlaylistResult


@dataclass
class PublishResult:
    url: str
    added: int = 0
    warnings: list[str] = field(default_factory=list)


def create_youtube_playlist(config: AppConfig, result: PlaylistResult, logger=None) -> PublishResult:
    # NOT: YOUTUBE_DATA_API_KEY burada ARANMIYOR. Playlist olusturma OAuth
    # kimlik bilgileriyle yapilir; API anahtari bu akista kullanilmaz.
    # Eskiden anahtar zorunlu tutuluyor ve gecerli yapilandirmalar reddediliyordu.
    if not (
        config.youtube_oauth_client_secret_file
        or (config.youtube_oauth_client_id and config.youtube_oauth_client_secret)
    ):
        raise RuntimeError(
            "Set YOUTUBE_OAUTH_CLIENT_SECRET_FILE or both YOUTUBE_OAUTH_CLIENT_ID and "
            "YOUTUBE_OAUTH_CLIENT_SECRET for official playlist creation"
        )

    try:
        from google.auth.transport.requests import Request
        from google.oauth2.credentials import Credentials
        from googleapiclient.discovery import build
        from googleapiclient.errors import HttpError
    except ImportError as exc:
        raise RuntimeError(
            "Google OAuth bağımlılıkları kurulu değil. `pip install -r requirements.txt` çalıştırın."
        ) from exc

    scopes = ["https://www.googleapis.com/auth/youtube"]
    credentials = _load_credentials(config, scopes, Credentials, Request, logger=logger)

    service = build("youtube", "v3", credentials=credentials, cache_discovery=False)
    playlist = (
        service.playlists()
        .insert(
            part="snippet,status",
            body={
                "snippet": {
                    "title": f"Learning Playlist: {result.topic}"[:150],
                    "description": "Generated by Make A Playlist",
                },
                "status": {"privacyStatus": config.youtube_playlist_privacy_status},
            },
        )
        .execute()
    )
    playlist_id = playlist["id"]
    url = f"https://www.youtube.com/playlist?list={playlist_id}"

    warnings: list[str] = []
    added = 0
    for recommendation in result.recommendations:
        try:
            service.playlistItems().insert(
                part="snippet",
                body={
                    "snippet": {
                        "playlistId": playlist_id,
                        "resourceId": {
                            "kind": "youtube#video",
                            "videoId": recommendation.video.video_id,
                        },
                    }
                },
            ).execute()
            added += 1
        except HttpError as exc:
            # Tek bir videonun eklenememesi tum playlist'i cope atmamali.
            # Eskiden ilk hata yukari firliyor, kullanicinin hesabinda yarim kalan
            # bir playlist ve hicbir URL bildirimi olmadan kaliyordu.
            warnings.append(
                f"'{recommendation.video.title}' playlist'e eklenemedi: {getattr(exc, 'reason', None) or exc}"
            )
            if logger:
                logger.warning("playlistItems.insert failed for %s: %s", recommendation.video.video_id, exc)

    if logger:
        logger.info("Created YouTube playlist %s with %s/%s items", url, added, len(result.recommendations))
    return PublishResult(url=url, added=added, warnings=warnings)


def _load_credentials(config: AppConfig, scopes: list[str], Credentials, Request, logger=None):
    token_path = Path(config.youtube_oauth_token_file)
    token_path.parent.mkdir(parents=True, exist_ok=True)

    credentials = None
    if token_path.exists():
        try:
            credentials = Credentials.from_authorized_user_file(str(token_path), scopes=scopes)
        except Exception as exc:
            if logger:
                logger.warning("Stored OAuth token could not be read: %s", exc)
            credentials = None

    if credentials and credentials.valid:
        return credentials

    if credentials and credentials.expired and credentials.refresh_token:
        try:
            credentials.refresh(Request())
            token_path.write_text(credentials.to_json(), encoding="utf-8")
            return credentials
        except Exception as exc:
            # Yenileme basarisizsa tam yetkilendirmeye geri don (eskiden burada takiliyordu).
            if logger:
                logger.warning("OAuth token refresh failed, re-authorising: %s", exc)

    if not config.youtube_oauth_allow_local_server:
        raise RuntimeError(
            "Geçerli bir OAuth token yok ve YOUTUBE_OAUTH_ALLOW_LOCAL_SERVER=false. "
            f"Yetkilendirmeyi yerel makinede yapıp token dosyasını `{token_path}` konumuna kopyalayın."
        )

    flow = _build_installed_app_flow(config, scopes)
    try:
        # UYARI: bu cagri bir tarayici acar ve SUNUCU tarafinda calisir.
        # Uzak/headless dagitimda YOUTUBE_OAUTH_ALLOW_LOCAL_SERVER=false yapin.
        credentials = flow.run_local_server(port=0, open_browser=True, timeout_seconds=300)
    except TypeError:
        # Eski google-auth-oauthlib surumleri `timeout_seconds` kabul etmiyor.
        credentials = flow.run_local_server(port=0)
    token_path.write_text(credentials.to_json(), encoding="utf-8")
    return credentials


def _build_installed_app_flow(config: AppConfig, scopes: list[str]):
    from google_auth_oauthlib.flow import InstalledAppFlow

    if config.youtube_oauth_client_secret_file:
        return InstalledAppFlow.from_client_secrets_file(config.youtube_oauth_client_secret_file, scopes=scopes)

    client_config = {
        "installed": {
            "client_id": config.youtube_oauth_client_id,
            "client_secret": config.youtube_oauth_client_secret,
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "redirect_uris": ["http://localhost"],
        }
    }
    return InstalledAppFlow.from_client_config(client_config, scopes=scopes)
